### ISSUE TITLE
Couple ideas

### ISSUE THREAD

**Issue by Bernhard40** [a13xp0p0v/kconfig-hardened-check#1]
Shouldn't [NAMESPACES](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kconfig-hardened-check.py#L94) be replaced by `USER_NS`? AFAIK only user namespaces have security concerns, others are fine. Disabling them all will negatively affect many applications which use various namespaces for sandboxing.

Since linux 4.16 there is `CC_STACKPROTECTOR_AUTO` kconfig which effectively replaces [CC_STACKPROTECTOR_STRONG](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kconfig-hardened-check.py#L54) and make it false negative in script.

Script doesn't check for [DEVMEM](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kspp-recommendations.config#L18) which when set to `n` make [STRICT_DEVMEM](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kconfig-hardened-check.py#L38) and [IO_STRICT_DEVMEM](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kconfig-hardened-check.py#L65) false negative.

**Comment by anthraxx** [comment]
On June 20, 2018 3:19:24 PM GMT+02:00, Bernhard40 <notifications@github.com> wrote:
>Shouldn't
>[NAMESPACES](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kconfig-hardened-check.py#L94)
>be replaced by `USER_NS`? AFAIK only user namespaces have security
>concerns, others are fine. Disabling them all will negatively affect
>many applications which use various namespaces for sandboxing.
>
>Since linux 4.16 there is `CC_STACKPROTECTOR_AUTO` kconfig which
>effectively replaces
>[CC_STACKPROTECTOR_STRONG](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kconfig-hardened-check.py#L54)
>and make it false negative in script.
>
>Script doesn't check for
>[DEVMEM](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kspp-recommendations.config#L18)
>which when set to `n` make
>[STRICT_DEVMEM](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kconfig-hardened-check.py#L38)
>and
>[IO_STRICT_DEVMEM](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kconfig-hardened-check.py#L65)
>false negative.

I already nearly finished a PR for DEVMEM and Stack Protector case by adding context aware logic to the option checks.
Pull request incoming but later today that will allow lot more conditional checks very easily.

**Comment by anthraxx** [comment]
@a13xp0p0v please no force push, that creates weird merge diffs when working on something :smile_cat:

**Comment by a13xp0p0v** [comment]
@Bernhard40 , thanks a lot for the ideas. I agree. Will fix namespaces mistake soon.
@anthraxx , thanks, cool! Waiting for your PR.
And, yes, no more force push from me.

**Comment by a13xp0p0v** [comment]
Closing, since @anthraxx PR will resolve it.
