### ISSUE TITLE
Feature request: Check CONFIG_RESET_ATTACK_MITIGATION

### ISSUE THREAD

**Issue by hannob** [a13xp0p0v/kconfig-hardened-check#11]
Thanks for this tool.

I'd propose to add a check for CONFIG_RESET_ATTACK_MITIGATION.
This is a feature that on modern systems will set a flag on boot that signals the BIOS to wipe the memory if an unclean shutdown happened. This can protect against some forms of cold boot attacks where you reboot into another system and try to read out the memory from the previous run.

Here's the Kernel submission with some explanation:
https://lwn.net/Articles/730006/

It's also explained in this talk:
https://www.youtube.com/watch?v=RqvPZnLkP70 (around minute 35)

**Comment by Bernhard40** [comment]
This option needs userspace support, otherwise it's not recommended for use:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a5c03c31af2291f13689d11760c0b59fb70c9a5a

https://bugzilla.redhat.com/show_bug.cgi?id=1532058

**Comment by hannob** [comment]
Interesting, is there any userspace tool to do this? Or is this basically unsupported in current systems?

**Comment by anthraxx** [comment]
@hannob I wanted to look into this for systemd, but forgot for quite a while. thanks for reminding me, back then there was no userspace support, theoretically you could add a systemd service but doing it _properly_ is bit more tricky. I'm putting this back onto my todo list and take a dive into how to properly implement this into systemd itself at a place that could guarantee that all other services etc. are already properly shut down.

**Comment by a13xp0p0v** [comment]
Hello @hannob @Bernhard40 @anthraxx,

`RESET_ATTACK_MITIGATION` is a nice option, I will add this check to the script with a comment about userspace support.

That case will be similar to the `STATIC_USERMODEHELPER` option, which needs the userspace support as well (but, as I know, enabling it currently breaks systemd workflow on Ubuntu).

**Comment by a13xp0p0v** [comment]
Hm... By the way Ubuntu 18 has `RESET_ATTACK_MITIGATION` enabled.

**Comment by anthonyryan1** [comment]
5 years later...

Has anyone got the userland support for this feature up and running yet?

I'm interested in solutions for either OpenRC or systemd. There's plenty of mentions of the kconfig option, but I can't find any mention of the userland half of this feature.

**Comment by a13xp0p0v** [comment]
@anthonyryan1, it looks like multiple GNU/Linux distros already have this option enabled:
```
$ grep -r RESET_ATTACK_MITIGATION kernel_hardening_checker/config_files/distros/|grep "=y"
kernel_hardening_checker/config_files/distros/Debian_13_Trixie_aarch64.config:CONFIG_RESET_ATTACK_MITIGATION=y
kernel_hardening_checker/config_files/distros/Oracle_Linux_10_(UEK-NEXT)_aarch64.config:CONFIG_RESET_ATTACK_MITIGATION=y
kernel_hardening_checker/config_files/distros/Ubuntu_25.04_Oracular_aarch64.config:CONFIG_RESET_ATTACK_MITIGATION=y
kernel_hardening_checker/config_files/distros/Arch_hardened_x86_64.config:CONFIG_RESET_ATTACK_MITIGATION=y
kernel_hardening_checker/config_files/distros/Azure_Linux_x86_64.config:CONFIG_RESET_ATTACK_MITIGATION=y
kernel_hardening_checker/config_files/distros/nixpkgs-linux_hardened.config:CONFIG_RESET_ATTACK_MITIGATION=y
kernel_hardening_checker/config_files/distros/Debian_13_Trixie_x86_64.config:CONFIG_RESET_ATTACK_MITIGATION=y
kernel_hardening_checker/config_files/distros/Ubuntu_24.04_LTS_Noble_riscv64.config:CONFIG_RESET_ATTACK_MITIGATION=y
kernel_hardening_checker/config_files/distros/Ubuntu_25.04_Plucky_x86_64.config:CONFIG_RESET_ATTACK_MITIGATION=y
kernel_hardening_checker/config_files/distros/Ubuntu_20.04_LTS_Focal_x86_64.config:CONFIG_RESET_ATTACK_MITIGATION=y
kernel_hardening_checker/config_files/distros/Ubuntu_20.04_LTS_Focal_aarch64.config:CONFIG_RESET_ATTACK_MITIGATION=y
```

**Comment by anthonyryan1** [comment]
@a13xp0p0v  The thing I'm referring to is the heavily suggested userland component  [described in the kernel config](https://github.com/torvalds/linux/blob/v6.12/drivers/firmware/efi/Kconfig#L176-L187):

"This should only be enabled when userland is configured to  clear the MemoryOverwriteRequest flag on clean shutdown after secrets have been evicted, since otherwise it will trigger even on clean reboots."

I'm curious if that userland component even exists?

From a security perspective, we're not doing anything wrong by enabling the feature. It'll still clear the RAM between reboots. But we're clearing the RAM on every clean reboot, which can be rather slow with 1 TB of RAM in a machine, not just during a reset attack.
