### ISSUE TITLE
CONFIG_MODULE_SIG_FORCE shouldn't be checked if CONFIG_MODULES is not set

### ISSUE THREAD

**Issue by hannob** [a13xp0p0v/kconfig-hardened-check#12]
I have a minimal kernel without modules for a server. I get a warning about CONFIG_MODULE_SIG_FORCE, which should not apply for a kernel without module support.

For several other module-related options the script behaves correctly (saying 'CONFIG_MODULES: OK ("is not set")' indicating this does not apply), but for CONFIG_MODULE_SIG_FORCE it does not do so.

Output is:
```
  CONFIG_MODULE_SIG_FORCE                |      y      |   kspp   |  self_protection   ||      FAIL: not found       
```

**Comment by a13xp0p0v** [comment]
Fixed.
Thank you @hannob.
