### ISSUE TITLE
CONFIG_STATIC_USERMODEHELPER

### ISSUE THREAD

**Issue by anthonyryan1** [a13xp0p0v/kconfig-hardened-check#33]
I read over the CLIP OS notes regarding this option, and they also mention that they are not currently using it in the second paragraph.

It seems to be that this option isn't actually helpful unless you've already got a usermode helper program?

Just questioning the wisdom of this option as I imagine some people will just enable everything they see here, and may wind up with this pointing at a non-existent binary.

**Comment by Bernhard40** [comment]
Yes, this option needs userspace support and yes, blindly enabling everything may cause harm.

**Comment by a13xp0p0v** [comment]
@Bernhard40, absolutely agree.
N.B. There is a comment about `STATIC_USERMODEHELPER` in the source code:
```
checklist.append(OptCheck('STATIC_USERMODEHELPER', 'y', 'clipos', 'self_protection')) # needs userspace support (systemd)
```
