### ISSUE TITLE
conflict with the latest grsecurity

### ISSUE THREAD

**Issue by pythonmandev** [a13xp0p0v/kconfig-hardened-check#37]
CONFIG_REFCOUNT_FULL conflict with PAX_REFCOUNT
PAGE_TABLE_ISOLATION conflict with PAX_MEMORY_UDEREF
VMAP_STACK conflict with GRKERNSEC_KSTACKOVERFLOW
SECURITY_YAMA conflict with GRKERNSEC
RANDOMIZE_BASE also can not enable.

**Comment by a13xp0p0v** [comment]
Hello @pythonmandev!
What do you mean saying "latest grsecurity"?

**Comment by anthraxx** [comment]
its not an openly available patchset anymore hence i suggest to not take it into account. I would think differently if it would be open source, but sadly its not.
