### ISSUE TITLE
Please support /proc/config.gz

### ISSUE THREAD

**Issue by morfikov** [a13xp0p0v/kconfig-hardened-check#47]
Currently only uncompressed `config-*` files in /boot/ are supported, but the current kernel config can also be accessed via `/proc/config.gz` . There's no way to use this file. Please support this path as well.

**Comment by a13xp0p0v** [comment]
No problem, I would recommend this:
```
  # zcat /proc/config.gz >  my.config
  # ./bin/kconfig-hardened-check -c my.config
```

**Comment by morfikov** [comment]
Yes, I know, but this is the same as just using `-c /boot/config-*` . I thought of using `/proc/config.gz` because in such case a user would just use one file no matter what kernel version he's using. When you decompress the file first, it's an extra step which could be eliminated to simplify the whole process and make it easier.

**Comment by a13xp0p0v** [comment]
Not all kernels provide the kernel config via `/proc/config.gz`.
For example, RHEL, Fedora, Ubuntu, Debian don't do that.

I think we can use `zcat` separately, if we need.
