### ISSUE TITLE
Color indicators for "check result" column

### ISSUE THREAD

**Issue by harisphnx** [a13xp0p0v/kconfig-hardened-check#81]
Would the maintainers be open to adding colors to the output of the "check result" column? For example, the output would be red for FAIL, and green for OK?

**Comment by harisphnx** [comment]
If so, I can make the change and create a PR

**Comment by a13xp0p0v** [comment]
Yes, it would be nice.
Looking forward to your PR.

**Comment by frakman1** [comment]
Has anyone done this yet?
I made a hacky attempt of this last year before the `sysctl` support was added. I added different colors for the two sections too:

<img width="1282" alt="image" src="https://github.com/a13xp0p0v/kconfig-hardened-check/assets/5826484/e880006a-5f1d-4580-b3e2-dcc0b104b089">

**Comment by a13xp0p0v** [comment]
@frakman1 thanks, it looks nice.
Could you give a link to your commit, I'll help to rebase it.

**Comment by frakman1** [comment]
Thank you @a13xp0p0v. 
I just checked and my changes were based on [this](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/899752c13f4d1260d1a33985672b72b3a9cb60ec/kconfig_hardened_check/__init__.py) commit:
```
* 899752c - (Sun Oct 2 21:45:13 2022 +0300) Also check 'nospectre_v2' with 'spectre_v2' - <Alexander Popov> (HEAD -> master, origin/master, origin/HEAD)
```

Original File (rename to .py):
[__init__.txt](https://github.com/a13xp0p0v/kconfig-hardened-check/files/12506520/__init__.txt)


Colored File (rename to .py):
[__init__.color.txt](https://github.com/a13xp0p0v/kconfig-hardened-check/files/12506521/__init__.color.txt)

I created a patch file using:
```
git diff --no-index --patch --output=color.diff __init__.py __init__.color.py
```

patch file (optionally rename to .diff):
[color.txt](https://github.com/a13xp0p0v/kconfig-hardened-check/files/12506530/color.txt)

**Comment by a13xp0p0v** [comment]
Thanks, I see the approach.

Let's print OK results in green and FAIL results in red.

We need to modify the `table_print()` method of classes in [engine.py](https://github.com/a13xp0p0v/kconfig-hardened-check/blob/master/kconfig_hardened_check/engine.py).

I would recommend something like that:

1) defining ANSI escape sequences at the beginning of the file:
```
GREEN_COLOR = '\x1b[32m'
RED_COLOR = '\x1b[31m'
END_COLOR = '\x1b[0m'
```

2) modify printing methods this way:
```
if with_results:
    if self.result.startswith('OK'):
        color = GREEN_COLOR
    elif self.result.startswith('FAIL:'):
        color = RED_COLOR
    else:
        assert(False), f'unexpected result "{self.result}"'
    colored_result = f'{color}{self.result}{END_COLOR}'
    print(f'| {colored_result}', end='')
```

What do you think?
Would you like to prepare a pull request?

Thanks!

**Comment by trclst** [comment]
I would only going to color `OK `and `FAIL` not full line.
Besides, I don't know if there aren't more important things a `| grep FAIL` can do.
Maybe it is better to keep the code small, the information is still there whether in color or not.
Anyway hope it looks fancy.

**Comment by frakman1** [comment]
If you only want to see the failures, you can use the `-m show_fail` option

**Comment by frakman1** [comment]
> What do you think? Would you like to prepare a pull request?

I like it. Thank you for the guidance. I just attempted it and it seems I have to repeat that logic in three places before I could get all the prints.

sample output:

<img width="1047" alt="image" src="https://github.com/a13xp0p0v/kconfig-hardened-check/assets/5826484/d098d14f-2e1a-4569-af22-54ef2bc0eecb">

Diffs located in my fork [here](https://github.com/frakman1/kconfig-hardened-check/compare/108eb7374967b0f66e70b68cca60a0548f12844c...71c8e35842b805e8e6b819bf599b07fdd0d48479). 

Let me know if that looks good. If so, I will issue a pull request.

**Comment by a13xp0p0v** [comment]
Thanks @frakman1 !

I would propose creating a function `colorize_result()` and call several times to avoid copying the code.

**Comment by frakman1** [comment]
I've made the changes. The new diffs are [here](https://github.com/frakman1/kconfig-hardened-check/compare/71c8e35842b805e8e6b819bf599b07fdd0d48479...f45482fb9d3ac64fa386b896859d69d9ca2013af):

**Comment by frakman1** [comment]
I've updated the code with your recommendations. See changes [here](https://github.com/frakman1/kconfig-hardened-check/commit/fb9aeb5392762c6ea3aa67096a18e163e63ec6ea)

**Comment by a13xp0p0v** [comment]
I've left some comments. The main point: it's better to leave printing inside of the `table_print()` method. The `colorize_result()` function should only return the colored string.

**Comment by frakman1** [comment]
Changes applied [here](https://github.com/frakman1/kconfig-hardened-check/compare/108eb7374967b0f66e70b68cca60a0548f12844c..d3e04de12f28c914f8fb9acd1a6eac8fc9b4ca8b)

**Comment by a13xp0p0v** [comment]
Good!

Please remove the unneeded whitespaces and send the pull request.

Looking forward to it.

**Comment by frakman1** [comment]
Done.
https://github.com/a13xp0p0v/kconfig-hardened-check/pull/86
